// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 8,
                            Description = "Soft, Long-hair, Lynx-point Neva Masquerade Siberian cat. Beauty, grace, and silly all at once. Was absolutely royalty in a past life.",
                            Gender = "Female",
                            Name = "Kimmy"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 2,
                            Description = "Silly chonker. Very food motivated but a lovely companion and sweet natured. Is the yang to Betty's Yin- brother and sister- must adopt together.",
                            Gender = "Male",
                            Name = "Max"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 2,
                            Description = "Sweet lil angel. Can be anxious around crowds or new people but is so sweet and demure when comfy. LOVES worm toy. Is the yin to Max's Yang- brother and sisters- must adopt together.",
                            Gender = "Female",
                            Name = "Betty"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 1,
                            Description = "Silly cute goof. Loves to cuddle and play. Little sweet ragdoll.",
                            Gender = "Male",
                            Name = "Spike"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 1,
                            Description = "Big fluff and like bird toys. will eat any food in sight but is so sweet and lovey you won't even mind. Will be a chonker one day.",
                            Gender = "Male",
                            Name = "Angel"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 8,
                            Description = "Lovely sweet baby- loves pets and licking the carpet lol.",
                            Gender = "Female",
                            Name = "Cupcake",
                            Size = "Small"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 10,
                            Description = "Gentle pup with a lot of heart. Mr. loves Cupcake adn belly rubs.",
                            Gender = "Male",
                            Name = "Muffin",
                            Size = "Medium"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 2,
                            Description = "Cookie is gentle and polite. Loves to love.",
                            Gender = "Female",
                            Name = "Cookie",
                            Size = "Small"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 12,
                            Description = "The sweetest lil shih Tzu you'll ever meet. gets so excited to see you she pees a little but you don't mind cause its so sweet.",
                            Gender = "Female",
                            Name = "Emma",
                            Size = "Medium"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 7,
                            Description = "Flamboyant lil boy with a tendency for drama. Very excitable fun pup.",
                            Gender = "Male",
                            Name = "Frankenfurter",
                            Size = "Large"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.SmallAnimal", b =>
                {
                    b.Property<int>("SmallAnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SmallAnimalId");

                    b.ToTable("SmallAnimals");

                    b.HasData(
                        new
                        {
                            SmallAnimalId = 1,
                            Age = 1,
                            Description = "Guinea Pig. Lovely sweet boy to humans- but doesnt play well with other hams. Loves to burrow.",
                            Gender = "Male",
                            Name = "Bacon"
                        },
                        new
                        {
                            SmallAnimalId = 2,
                            Age = 3,
                            Description = "Bunny. loves play time and is very excitable.",
                            Gender = "Female",
                            Name = "Cardi Bun"
                        },
                        new
                        {
                            SmallAnimalId = 3,
                            Age = 1,
                            Description = "Hamster. Loves to sleep and eat. a Lazy silly boy but is full of so much love.",
                            Gender = "Male",
                            Name = "Hammond"
                        },
                        new
                        {
                            SmallAnimalId = 4,
                            Age = 4,
                            Description = "Chinchilla. Loves having lots of room to play and explore in! This baby is super fun and so so SOFT. ",
                            Gender = "Female",
                            Name = "Sage"
                        },
                        new
                        {
                            SmallAnimalId = 5,
                            Age = 1,
                            Description = "Rat. Intelligent social boy with a sense of adventure.",
                            Gender = "Male",
                            Name = "Goddric"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
